name: GitHubPages

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Check out WWW
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: www

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:  always

      - name: Install packages
        run:  npm install

      - name: Test
        run: npm test

      - name: Build
        run:  npm run build

      - name: Publish to GitHub Pages
        if: github.ref_name == 'master'
        working-directory: www
        run: |
          rm -rf *
          cp -r ../bundle/* .
          rm *.map
          git add --all
          git config user.email "none"
          git config user.name "GitHub Pages Publisher"
          git -C .. log -1 --format="%h: %s" > ../.commit
          git diff-index --quiet HEAD || git commit -F ../.commit
          git push
