name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Check out WWW
        if:   github.ref_name == 'main'
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: www

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key:  always

      - name: Install packages
        run:  npm install

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          command: npm test
          max_attempts: 3
          timeout_seconds: 27

      - name: Build
        run:  npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: ./bundle

      - name: Create commit message
        if:   github.ref_name == 'main'
        run:  |
          git log -1 --format="%h: %s" > .commit

      - name: Publish to GitHub Pages
        if:   github.ref_name == 'main'
        working-directory: www
        run: |
          rm -rf *
          touch .nojekyll
          cp -r ../bundle/* .
          rm *.map
          git add --all
          git config user.email "none"
          git config user.name "GitHub Pages Publisher"
          git diff-index --quiet HEAD || git commit -F ../.commit
          git push
